export const ADD_COURSE = 'ADD_COURSE';
export const LOAD_COURSE = 'LOAD_COURSE';
export const LOAD_PASSENGER_LIST = 'LOAD_PASSENGER_LIST';
export const ADD_NEW_PASEENGER = 'ADD_NEW_PASEENGER';
export const GET_FLIGHT_LIST = 'GET_FLIGHT_LIST';
export const GET_FLIGHT_DETAILS = 'GET_FLIGHT_DETAILS';
export const UPDATE_FLIGHT_DETAILS = 'UPDATE_FLIGHT_DETAILS';
export const GET_SEAT_MAP_DETAILS = 'GET_SEAT_MAP_DETAILS';
export const GET_SEAT_MAP_ALLOCATION_DETAILS =
  'GET_SEAT_MAP_ALLOCATION_DETAILS';
export const UPDATE_SEAT_MAP = 'UPDATE_SEAT_MAP';
export const UPDATE_PASSENGER = 'UPDATE_PASSENGER';
export const GET_LOGIN_INFORMATION = 'GET_LOGIN_INFORMATION';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_CURRENT_USER = 'GET_CURRENT_USER';
export const FILTER_PASSENGER = 'FILTER_PASSENGER';
export const LOGOUT_USER = 'LOGOUT_USER';
